UV-10 -Update algo for cocos
ultravioletrs/ai pull request #11
Opened 2024-08-05 15:42 UTC by FilipCivljak

resolves: #10

2024-08-12 10:23 UTC, SammyOina reviewed
please update readme with instructions for where to place datasets once downloaded

2024-08-12 11:03 UTC, SammyOina requested changes
add a requirements file

2024-08-12 12:42 UTC, SammyOina requested changes
fix typos in readme file, also include step by step actions to take when testing with cocos

2024-08-12 12:43 UTC, SammyOina requested changes

2024-08-12 12:43 UTC, SammyOina commented on requirements.txt
limit to minimum requirements required for file
```
numpy==2.0.0
pandas==2.2.2
scikit-learn==1.5.1
torch==2.3.1
joblib==1.4.2
matplotlib==3.9.1
```

2024-08-12 13:40 UTC, SammyOina requested changes

2024-08-12 13:40 UTC, SammyOina commented on rul-turbofan/requirements.txt
> +seaborn==0.13.2
add an empty line at the end

2024-08-20 10:27 UTC, rodneyosodo requested changes
Update workflows

- https://github.com/ultravioletrs/ai/blob/main/.github/dependabot.yaml
- https://github.com/ultravioletrs/ai/blob/main/.github/workflows/python.yaml

2024-09-11 12:15 UTC, dborovcanin commented
@FilipCivljak Please rebase and resolve comments.

2024-09-11 15:55 UTC, dborovcanin commented
@SammyOina Please review.

2024-09-11 22:40 UTC, drasko commented
@SammyOina please review

2024-09-11 22:42 UTC, drasko commented
@SammyOina please review

2024-09-16 07:36 UTC, SammyOina requested changes

2024-09-16 07:36 UTC, SammyOina commented on .github/workflows/python.yaml
> +      - "rul-turbofan"/**"
```suggestion
      - "rul-turbofan/**"
```

2024-09-16 07:36 UTC, SammyOina commented on .github/workflows/python.yaml
> +      - "rul-turbofan"/**"
```suggestion
      - "rul-turbofan/**"
```

2024-09-18 20:41 UTC, rodneyosodo requested changes

2024-09-18 20:41 UTC, rodneyosodo commented on rul-turbofan/README.md
> +unzip results.zip -d results
Close the code block

2024-09-18 20:41 UTC, rodneyosodo commented on rul-turbofan/README.md
> +  ```
Add new line after the code block

2024-09-23 13:45 UTC, SammyOina approved these changes

2024-09-23 13:47 UTC, merged