NOISSUE - Support Cocos FileSystem
ultravioletrs/ai pull request #12
Opened 2024-08-06 07:17 UTC by rodneyosodo

This update introduces significant enhancements to support the Cocos AI system, focusing on documentation, dependency management, and conditional feature logic. Key changes allow for dynamic dataset paths and improved modularity in handling machine learning algorithms.

- **New Features**
	- Added support for the Cocos AI system with new documentation and features for secure workload execution.
	- Introduced conditional dataset loading and artifact management based on the Cocos feature across various algorithms.
	- Enhanced flexibility in handling dataset paths and metrics rendering for training processes.

- **Bug Fixes**
	- Improved error handling for dataset file access and parsing operations.

- **Documentation**
	- Added comprehensive documentation for the Cocos AI system including setup and operation instructions in `COCOS.md`.
	- Updated the README to reflect new Cocos integrations and examples.

- **Chores**
	- Updated dependencies and feature configurations across multiple projects to include local libraries and new functionalities.

- **Tests**
	- Add unit tests for the new functions in the lib module, including sending data via a Unix socket and saving results to a file.

2024-08-06 09:11 UTC, WashingtonKK requested changes

2024-08-06 09:11 UTC, WashingtonKK commented on burn-algorithms/addition-inference/Cargo.toml
> +lib = { path = "../lib" }
Add new line.

2024-08-06 09:11 UTC, WashingtonKK commented on burn-algorithms/addition/Cargo.toml
> +lib = { path = "../lib" }
Add new line.

2024-08-06 09:11 UTC, WashingtonKK commented on burn-algorithms/imdb/Cargo.toml
> +lib = { path = "../lib" }
Same here

2024-08-06 09:11 UTC, WashingtonKK commented on burn-algorithms/mnist/Cargo.toml
> +lib = { path = "../lib" }
New line

2024-08-12 10:57 UTC, SammyOina approved these changes

2024-08-12 17:40 UTC, merged