NOISSUE - Add wasm Inference
ultravioletrs/ai pull request #3
Opened 2024-07-04 18:53 UTC by rodneyosodo

## Summary

- **New Features**
  - Added a section on using `wasmtime` runtime for WebAssembly binaries.

- **Bug Fixes**
  - Updated model paths for Iris and MNIST training artifacts to ensure correct directory structure.

- **Documentation**
  - Enhanced README file with detailed guides for dataset handling and inference.

- **New Implementations**
  - Added example programs for Iris and MNIST dataset inference using Rust and WebAssembly.
  - Introduced image conversion functionality to extract and print pixel data.

### Dataset Inference

```mermaid
sequenceDiagram
    participant User
    participant Main
    participant Infer
    participant Model

    User->>Main: Start Iris Inference
    Main->>Infer: Deserialize Input
    Infer->>Model: Load pre-trained model
    Infer->>Model: Perform forward propagation
    Model->>Infer: Return predicted class
    Infer->>Main: Map class to label
    Main->>User: Display Inference Result
```

2024-07-04 19:35 UTC, drasko requested changes

2024-07-04 19:35 UTC, drasko commented on burn-algorithms/mnist-wasm-inference/4.png
Do we need this binary file here? Is data downloadable from somewhere - i.e. form Kaggle - and if yes, and if you use this data for training, then something like this should be downloaded and used for inference, too.

2024-07-04 20:05 UTC, rodneyosodo commented on burn-algorithms/mnist-wasm-inference/4.png
It is downloadable from Kaggle and documented in this section https://github.com/ultravioletrs/ai/blob/main/burn-algorithms/README.md#mnist-dataset

I copied the image from the dataset and added it as an example. We use that image to generate the array of pixels to make inference on our model

2024-07-06 20:04 UTC, drasko approved these changes
LGTM

2024-07-06 20:04 UTC, merged