NOISSUE - Test Covid19 on Cocos
ultravioletrs/ai pull request #8
Opened 2024-07-24 11:54 UTC by rodneyosodo

This pull request refactors the COVID-19 detection model code to enhance modularity and readability, adds support for Unix socket-based inference, and updates the documentation with comprehensive setup and usage instructions.

- **Enhancements**:
    - Refactored `covid19.py` to support both model training and inference via a Unix socket.
    - Updated `predict.py` to allow loading model weights from a binary file generated by Cocos.
    - Improved dataset preparation and training logic in `covid19.py` for better modularity and readability.
- **Documentation**:
    - Expanded `README.md` with detailed setup instructions, including virtual environment setup, dataset preparation, model training, and testing with Cocos.
- **Bug Fixes**
	- Improved image selection logic and error handling in model preparation.
- **Chores**
	- Updated `.gitignore` to streamline file tracking.
	- Added `matplotlib` as a new dependency in the requirements.

2024-07-25 11:54 UTC, SammyOina requested changes

2024-07-25 11:54 UTC, SammyOina commented on covid19/README.md
> +The folders `data/h1`, `data/h1` or `data/h1` can be passed as zipped files (after they have been zipped) for example:
add documentation on zipping the directories correctly

2024-07-25 14:11 UTC, SammyOina requested changes

2024-07-25 14:11 UTC, SammyOina commented on covid19/README.md
> +python covid19.py --model model.pth data/h1 data/h2 data/h3
this fails

```shell
python covid19.py --model model.pth data/h1 data/h2 data/h3                                                                                                                                           1 ✘  mypy  
Traceback (most recent call last):
  File "/home/sammyk/Documents/ai/covid19/covid19.py", line 216, in <module>
    main()
  File "/home/sammyk/Documents/ai/covid19/covid19.py", line 161, in main
    with zipfile.ZipFile(hospital, "r") as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1331, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'data/h1'
```

2024-07-25 14:14 UTC, WashingtonKK commented on covid19/README.md
> +mkdir -p /tmp/covid19-test && cd /tmp/covid19-test
Testing on this folder results in this error:

```shell
&{message:"                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/algorithm3912989560\", line 53, in __init__\n    self.images[class_name] = get_images(class_name)\n                              ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/algorithm3912989560\", line 44, in get_images\n    for x in os.listdir(dir_path)\n             ^^^^^^^^^^^^^^^^^^^^\n"  computation_id:"1"  level:"ERROR"  timestamp:{seconds:1721858799  nanos:921433577}}
received agent log
&{message:"FileNotFoundError: [Errno 2] No such file or directory: '/tmp/work/data/Normal'\n"  computation_id:"1"  level:"ERROR"  timestamp:{seconds:1721858799  nanos:921444087}}
```

2024-08-12 14:50 UTC, SammyOina requested changes

2024-08-12 14:50 UTC, SammyOina commented on covid19/predict.py
>      show_image_with_prediction(image_path, predicted_class)
write to file instead in results directory

2024-08-13 15:53 UTC, SammyOina requested changes

2024-08-13 15:53 UTC, SammyOina commented on covid19/README.md
> +## Testing with Cocos
also add testing with prism

2024-08-15 08:16 UTC, SammyOina approved these changes

2024-08-15 13:16 UTC, merged